name: Approve PRs
on:
  workflow_dispatch:
  issue_comment:                                     
    types: [created, edited]

jobs:
  autoapprove:
    # This job only runs for pull request comments
    name: PR comment
    if: ${{ github.event.issue.pull_request }}
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Check
        if: |
          contains(github.event.comment.body, 'LGTM') && contains(github.event.comment.user.login, 'germa89')
        run: |
          echo "Run action"
      - uses: hmarr/auto-approve-action@v3
        if: |
          contains(github.event.comment.body, 'LGTM') && contains(github.event.comment.user.login, 'germa89')
        with:
          review-message: "Auto approved automated PR"
          pull-request-number: ${{ github.event.issue.number }}