name: "Release"

on:
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: Release
        options: 
        - 'Major'
        - 'Minor'
        - 'Patch'
        required: true

env:
  MAIN_PYTHON_VERSION: 3.9

jobs:
  bumpver:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout project
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.MAIN_PYTHON_VERSION }}

      - name: Install requirements
        run: |
          python -m pip install -U pip
          python -m pip install \
          git+https://github.com/jorgepiloto/bumpver.git@14850287a1ef3cc3848e5d0cc9317d4a228d2759

      - name: Release patch version
        run: |

          latest_version=0.0
          for branch in $(git branch | grep "release/"); do
                  version="${branch##release/}"
                  if [[ $version -ge $latest_version ]]; then
                          latest_version=version
                  fi
          done
          echo "::set-output name=latest_version::$latest_version"
        id: getter-version

      - name: Echo previous var
        run: |
          latest_version=${{ steps.getter-version.outputs.latest_version }}
          echo "Latest version is $latest_version"
