on:
  workflow_dispatch:
    inputs:
      new_version:
        description: 'Semantic Version Number X.Y.Z'
        required: true
        type: string

env:
  MAIN_PYTHON_VERSION: 3.9

jobs:
  print-tag:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout project
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.MAIN_PYTHON_VERSION }}

      - name: Install requirements
        run: |
          python -m pip install -U pip
          python -m pip install \
          git+https://github.com/jorgepiloto/bumpver.git@93dcdeb5ff76bb58fa617d4939561ecc60ef8720

      - name: Print the input tag to STDOUT
        run: echo  The tags are ${{ github.event.inputs.new_version }}

      - name: Test upgrade version
        run: |
          bumpver test '0.1.dev0' 'MAJOR.MINOR[.PATCH][.TAGNUM]' --tag=final
