on:
  workflow_dispatch:
    inputs:
      new_version:
        description: 'Semantic Version Number X.Y.Z'
        required: true
        type: string

env:
  MAIN_PYTHON_VERSION: 3.9
  NEW_VERSION: ${{ github.event.inputs.new_version }}

jobs:
  print-tag:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout project
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.MAIN_PYTHON_VERSION }}

      - name: Install requirements
        run: |
          python -m pip install -U pip
          python -m pip install \
          git+https://github.com/jorgepiloto/bumpver.git@14850287a1ef3cc3848e5d0cc9317d4a228d2759

      - name: Print the input tag to STDOUT
        run: echo  The tags are 

      - name: Get new major, minor and patch
        run: |
          NEW_VERSION_STR=($(echo "${{ env.NEW_VERSION }}" | tr "." "\n"))
          echo "New Major = ${NEW_VERSION_STR[0]}"
          echo "New Minor = ${NEW_VERSION_STR[1]}"
          echo "New Patch = ${NEW_VERSION_STR[2]}"

      - name: Evaluate current version numbers
        run:
             eval $(bumpver show --env)
